# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Riceneeder
avatar: http://q1.qlogo.cn/g?b=qq&nk=845541909&s=640
subtitle: 'å¯‚é™ä¹‹åœ°ï¼Œè¿›æ¥è¯·å®‰é™ | gankun.cn.ma'
description:  åˆ†äº«ä¸€äº›ä¸­åŒ»è¯çŸ¥è¯†æ–‡ç« ä¸å°éƒ¨åˆ†ç”µè„‘ç›¸å…³çš„å°ç‚¹
keywords: ä¸­åŒ»è¯
author: æ¢µé«˜å…ˆç”Ÿ
language: 
- zh-CN
- en
timezone:
email: 845541909@qq.com
favicon: https://q1.qlogo.cn/g?b=qq&nk=845541909&s=640

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://gankun.cn.ma
root: /
permalink: :abbrlink.html
permalink_defaults:

# Directory
# wiki_dir: wiki
# source_dir: source
# public_dir: public
# tag_dir: tags
# archive_dir: archives
# category_dir: categories
# code_dir: downloads/code
# i18n_dir: :lang
# skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 5
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination


# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
#theme: volantis
theme: aomori-up

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:

# # abbrlink config
abbrlink:
   alg: crc16 #support crc16(default) and crc32
   rep: hex    #support dec(default) and hex

# article:
#   # npm i hexo-related-popular-posts
#   related_posts:
#     enable: true
#     title: æ‚¨å¯èƒ½æ„Ÿå…´è¶£çš„æ–‡ç« 

# Dplayer
# hexo-tag-dplayer:
#   cdn:
#     - https://cdn.jsdelivr.net/npm/dplayer/dist/DPlayer.min.js
#     - https://cdn.jsdelivr.net/npm/dplayer/dist/DPlayer.min.css
#   default: 
#     # api: https://api.prprpr.me/dplayer/
#     loop: false
#     screenshot: false

import:
  head_begin:
  - <meta name="referrer" content="no-referrer">
#======================config for aomori-up
# highlight:
#   enable: false

aomori_menu:
  Home: /
  å½’æ¡£: archives/
  ç›¸å†Œ: photos/
  å‹é“¾: link/
  å…³äº: about/

aomori_social:
  -
    icon: logo-github
    url: https://github.com/Riceneeder
  -
    icon: logo-rss
    url: /atom.xml
  -
    icon: mail-outline
    url: mailto:845541909@qq.com
  - 
    icon: cloud-download-outline
    url: https://download.gankun.cn.ma

aomori_widgets:
  - toc # æ–‡ç« å¯¼èˆª
  - category  #æ–‡ç« åˆ†ç±»
  - tag # æ–‡ç« æ ‡ç­¾
  - recent_posts  # æœ€æ–°æ–‡ç« 
  - archive #æ–‡ç« å½’æ¡£

aomori_copyright: true # or false
aomori_busuanzi: true
aomori_favicon: ğŸ€
aomori_baidu_sitepush: true

beaudar:
  repo: Riceneeder/blog-comments
  issue-term: pathname
  issue-number:
  branch: main
  position: top
  order: desc
  theme:
    light: github-light
    dark: github-dark
  label: âœ¨ğŸ’¬âœ¨
